### ISSUE TITLE
Error when trying to run tests locally

### ISSUE THREAD

**Issue by sahilkhosla** [getshifter/alexa-shifterman#5]
```javascript
✘  ~/dev/alexa-shifterman  ./node_modules/mocha/bin/_mocha tests/conversation/


  Executing conversation: Alexa Shifter man
    ✓ Finished executing conversation

  Executing conversation: Alexa Shifter man
Uncaught exception: SyntaxError: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/sahil/dev/alexa-shifterman/src/handlers/default/GetNewsIntent.js:33:29
    at IncomingMessage.<anonymous> (/Users/sahil/dev/alexa-shifterman/src/handlers/default/GetNewsIntent.js:18:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/Users/sahil/dev/alexa-shifterman/node_modules/alexa-sdk/lib/alexa.js:300
    throw err;
    ^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/sahil/dev/alexa-shifterman/src/handlers/default/GetNewsIntent.js:33:29
    at IncomingMessage.<anonymous> (/Users/sahil/dev/alexa-shifterman/src/handlers/default/GetNewsIntent.js:18:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by sahilkhosla** [comment]
Probably because this url in `GetNewsIntent.js` is throwing a 404 - https://getshifter.io/wp-json/wp/v2/posts

**Comment by hideokamoto** [comment]
Thanks for reporting the issue :)
I've fixed the problem 👍
